"""production platform primitives

Revision ID: 7c98a56b9720
Revises: e5fa64ce26ec
Create Date: 2026-07-16 16:53:59.963212
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7c98a56b9720"
down_revision: str | Sequence[str] | None = "e5fa64ce26ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("resource_type", sa.String(length=120), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(op.f("ix_audit_events_actor_id"), "audit_events", ["actor_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_table(
        "crawl_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("schedule_cron", sa.String(length=120), nullable=True),
        sa.Column("schedule_timezone", sa.String(length=80), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_crawl_definitions_enabled"), "crawl_definitions", ["enabled"], unique=False
    )
    op.create_index(
        op.f("ix_crawl_definitions_next_run_at"), "crawl_definitions", ["next_run_at"], unique=False
    )
    op.create_table(
        "index_builds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "building",
                "verifying",
                "succeeded",
                "failed",
                "rolled_back",
                name="index_build_status",
            ),
            nullable=False,
        ),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("physical_index", sa.String(length=255), nullable=True),
        sa.Column("expected_documents", sa.Integer(), nullable=False),
        sa.Column("indexed_documents", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_index_builds_status"), "index_builds", ["status"], unique=False)
    op.create_table(
        "duplicate_clusters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("definition_id", sa.UUID(), nullable=True),
        sa.Column("representative_document_id", sa.UUID(), nullable=True),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["definition_id"], ["crawl_definitions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_duplicate_clusters_definition_id"),
        "duplicate_clusters",
        ["definition_id"],
        unique=False,
    )
    op.create_table(
        "web_resources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("definition_id", sa.UUID(), nullable=True),
        sa.Column("normalized_url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("host", sa.String(length=253), nullable=False),
        sa.Column("current_document_id", sa.UUID(), nullable=True),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_recrawl_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["definition_id"], ["crawl_definitions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("definition_id", "normalized_url", name="uq_resource_definition_url"),
    )
    op.create_index(
        op.f("ix_web_resources_current_document_id"),
        "web_resources",
        ["current_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_web_resources_definition_id"), "web_resources", ["definition_id"], unique=False
    )
    op.create_index(op.f("ix_web_resources_host"), "web_resources", ["host"], unique=False)
    op.create_index(
        op.f("ix_web_resources_last_changed_at"), "web_resources", ["last_changed_at"], unique=False
    )
    op.create_index(
        op.f("ix_web_resources_last_checked_at"), "web_resources", ["last_checked_at"], unique=False
    )
    op.create_index(
        op.f("ix_web_resources_next_recrawl_at"), "web_resources", ["next_recrawl_at"], unique=False
    )
    op.create_table(
        "metric_samples",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("metric_name", sa.String(length=120), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["crawl_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metric_samples_metric_name"), "metric_samples", ["metric_name"], unique=False
    )
    op.create_index(
        "ix_metric_samples_name_time",
        "metric_samples",
        ["metric_name", "observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_samples_observed_at"), "metric_samples", ["observed_at"], unique=False
    )
    op.create_index(op.f("ix_metric_samples_run_id"), "metric_samples", ["run_id"], unique=False)
    op.create_table(
        "operational_incidents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("open", "acknowledged", "resolved", name="incident_status"),
            nullable=False,
        ),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("incident_type", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["crawl_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_operational_incidents_incident_type"),
        "operational_incidents",
        ["incident_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operational_incidents_run_id"), "operational_incidents", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_operational_incidents_severity"),
        "operational_incidents",
        ["severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operational_incidents_status"), "operational_incidents", ["status"], unique=False
    )
    op.create_table(
        "pipeline_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("frontier_entry_id", sa.UUID(), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum("fetch", "extract", "index", name="pipeline_task_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ready",
                "leased",
                "retry_scheduled",
                "succeeded",
                "dead_lettered",
                "cancelled",
                name="pipeline_task_status",
            ),
            nullable=False,
        ),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.String(length=255), nullable=True),
        sa.Column("lease_token", sa.UUID(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rq_job_id", sa.String(length=255), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_error_type", sa.String(length=120), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["frontier_entry_id"], ["frontier_entries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["crawl_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "frontier_entry_id", "task_type", "generation", name="uq_pipeline_task_stage"
        ),
    )
    op.create_index(
        op.f("ix_pipeline_tasks_available_at"), "pipeline_tasks", ["available_at"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_tasks_frontier_entry_id"),
        "pipeline_tasks",
        ["frontier_entry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_tasks_lease_expires_at"),
        "pipeline_tasks",
        ["lease_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_tasks_lease_token"), "pipeline_tasks", ["lease_token"], unique=False
    )
    op.create_index(op.f("ix_pipeline_tasks_run_id"), "pipeline_tasks", ["run_id"], unique=False)
    op.create_index(
        "ix_pipeline_tasks_scheduler",
        "pipeline_tasks",
        ["status", "available_at", "task_type"],
        unique=False,
    )
    op.create_index(op.f("ix_pipeline_tasks_status"), "pipeline_tasks", ["status"], unique=False)
    op.create_index(
        op.f("ix_pipeline_tasks_task_type"), "pipeline_tasks", ["task_type"], unique=False
    )
    op.create_table(
        "domain_leases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("host", sa.String(length=253), nullable=False),
        sa.Column("lease_token", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["crawl_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["pipeline_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id"),
    )
    op.create_index(
        op.f("ix_domain_leases_expires_at"), "domain_leases", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_domain_leases_host"), "domain_leases", ["host"], unique=False)
    op.create_index(
        "ix_domain_leases_host_expiry",
        "domain_leases",
        ["run_id", "host", "expires_at"],
        unique=False,
    )
    op.create_index(op.f("ix_domain_leases_run_id"), "domain_leases", ["run_id"], unique=False)
    op.create_table(
        "worker_heartbeats",
        sa.Column("worker_id", sa.String(length=255), nullable=False),
        sa.Column("queues", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("current_task_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["current_task_id"], ["pipeline_tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("worker_id"),
    )
    op.create_index(
        op.f("ix_worker_heartbeats_current_task_id"),
        "worker_heartbeats",
        ["current_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_worker_heartbeats_last_seen_at"),
        "worker_heartbeats",
        ["last_seen_at"],
        unique=False,
    )
    op.create_table(
        "crawl_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("fetch_attempt_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "fetched", "not_modified", "failed", "robots_blocked", name="observation_outcome"
            ),
            nullable=False,
        ),
        sa.Column(
            "change_kind",
            sa.Enum(
                "initial", "unchanged", "metadata_only", "minor", "substantial", name="change_kind"
            ),
            nullable=True,
        ),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["fetch_attempt_id"], ["fetch_attempts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["resource_id"], ["web_resources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["crawl_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_crawl_observations_document_id"),
        "crawl_observations",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crawl_observations_fetch_attempt_id"),
        "crawl_observations",
        ["fetch_attempt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crawl_observations_observed_at"),
        "crawl_observations",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crawl_observations_outcome"), "crawl_observations", ["outcome"], unique=False
    )
    op.create_index(
        op.f("ix_crawl_observations_resource_id"),
        "crawl_observations",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crawl_observations_run_id"), "crawl_observations", ["run_id"], unique=False
    )
    op.create_index(
        "ix_observations_resource_observed",
        "crawl_observations",
        ["resource_id", "observed_at"],
        unique=False,
    )
    op.create_table(
        "extraction_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("fetch_attempt_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("parser_name", sa.String(length=80), nullable=False),
        sa.Column("parser_version", sa.String(length=40), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("promoted", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("text_length", sa.Integer(), nullable=True),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("error_type", sa.String(length=120), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["fetch_attempt_id"], ["fetch_attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["crawl_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "fetch_attempt_id", "parser_version", name="uq_extraction_parser_attempt"
        ),
    )
    op.create_index(
        op.f("ix_extraction_attempts_document_id"),
        "extraction_attempts",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extraction_attempts_fetch_attempt_id"),
        "extraction_attempts",
        ["fetch_attempt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extraction_attempts_run_id"), "extraction_attempts", ["run_id"], unique=False
    )
    op.create_table(
        "index_operations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "succeeded",
                "retry_scheduled",
                "dead_lettered",
                name="index_operation_status",
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["crawl_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "schema_version", name="uq_index_document_schema"),
    )
    op.create_index(
        op.f("ix_index_operations_available_at"), "index_operations", ["available_at"], unique=False
    )
    op.create_index(
        op.f("ix_index_operations_document_id"), "index_operations", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_index_operations_run_id"), "index_operations", ["run_id"], unique=False
    )
    op.create_index(
        "ix_index_operations_scheduler",
        "index_operations",
        ["status", "available_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_index_operations_status"), "index_operations", ["status"], unique=False
    )
    op.add_column("crawl_runs", sa.Column("definition_id", sa.UUID(), nullable=True))
    op.add_column(
        "crawl_runs",
        sa.Column("generation", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column(
        "crawl_runs",
        sa.Column("max_duration_seconds", sa.Integer(), server_default="3600", nullable=False),
    )
    op.add_column(
        "crawl_runs",
        sa.Column("global_concurrency", sa.Integer(), server_default="20", nullable=False),
    )
    op.add_column(
        "crawl_runs",
        sa.Column("per_domain_concurrency", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column(
        "crawl_runs",
        sa.Column(
            "allowed_content_types",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text('\'["text/html", "application/xhtml+xml"]\'::jsonb'),
            nullable=False,
        ),
    )
    op.add_column(
        "crawl_runs",
        sa.Column(
            "allowed_ports",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[80, 443]'::jsonb"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_crawl_runs_definition_id"), "crawl_runs", ["definition_id"], unique=False
    )
    op.create_foreign_key(
        "fk_crawl_runs_definition_id",
        "crawl_runs",
        "crawl_definitions",
        ["definition_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("documents", sa.Column("resource_id", sa.UUID(), nullable=True))
    op.add_column("documents", sa.Column("previous_version_id", sa.UUID(), nullable=True))
    op.add_column(
        "documents",
        sa.Column("version_number", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column(
        "documents",
        sa.Column("is_current", sa.Boolean(), server_default=sa.true(), nullable=False),
    )
    op.add_column(
        "documents",
        sa.Column(
            "change_kind",
            postgresql.ENUM(
                "initial",
                "unchanged",
                "metadata_only",
                "minor",
                "substantial",
                name="change_kind",
                create_type=False,
            ),
            server_default="initial",
            nullable=False,
        ),
    )
    op.add_column("documents", sa.Column("simhash", sa.String(length=16), nullable=True))
    op.add_column(
        "documents",
        sa.Column(
            "simhash_bands",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column("documents", sa.Column("duplicate_cluster_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_documents_change_kind"), "documents", ["change_kind"], unique=False)
    op.create_index(
        op.f("ix_documents_duplicate_cluster_id"),
        "documents",
        ["duplicate_cluster_id"],
        unique=False,
    )
    op.create_index(op.f("ix_documents_is_current"), "documents", ["is_current"], unique=False)
    op.create_index(op.f("ix_documents_resource_id"), "documents", ["resource_id"], unique=False)
    op.create_index(op.f("ix_documents_simhash"), "documents", ["simhash"], unique=False)
    op.create_foreign_key(
        "fk_documents_resource_id",
        "documents",
        "web_resources",
        ["resource_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_documents_previous_version_id",
        "documents",
        "documents",
        ["previous_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_documents_duplicate_cluster_id",
        "documents",
        "duplicate_clusters",
        ["duplicate_cluster_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "domain_states", sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "domain_states", sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "domain_states",
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "fetch_attempts",
        sa.Column(
            "request_headers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    for table_name, column_name in (
        ("crawl_runs", "generation"),
        ("crawl_runs", "max_duration_seconds"),
        ("crawl_runs", "global_concurrency"),
        ("crawl_runs", "per_domain_concurrency"),
        ("crawl_runs", "allowed_content_types"),
        ("crawl_runs", "allowed_ports"),
        ("documents", "version_number"),
        ("documents", "is_current"),
        ("documents", "change_kind"),
        ("documents", "simhash_bands"),
        ("domain_states", "consecutive_failures"),
        ("fetch_attempts", "request_headers"),
    ):
        op.alter_column(table_name, column_name, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fetch_attempts", "request_headers")
    op.drop_column("domain_states", "consecutive_failures")
    op.drop_column("domain_states", "last_failure_at")
    op.drop_column("domain_states", "last_success_at")
    op.drop_constraint("fk_documents_duplicate_cluster_id", "documents", type_="foreignkey")
    op.drop_constraint("fk_documents_previous_version_id", "documents", type_="foreignkey")
    op.drop_constraint("fk_documents_resource_id", "documents", type_="foreignkey")
    op.drop_index(op.f("ix_documents_simhash"), table_name="documents")
    op.drop_index(op.f("ix_documents_resource_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_is_current"), table_name="documents")
    op.drop_index(op.f("ix_documents_duplicate_cluster_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_change_kind"), table_name="documents")
    op.drop_column("documents", "duplicate_cluster_id")
    op.drop_column("documents", "simhash_bands")
    op.drop_column("documents", "simhash")
    op.drop_column("documents", "change_kind")
    op.drop_column("documents", "is_current")
    op.drop_column("documents", "version_number")
    op.drop_column("documents", "previous_version_id")
    op.drop_column("documents", "resource_id")
    op.drop_constraint("fk_crawl_runs_definition_id", "crawl_runs", type_="foreignkey")
    op.drop_index(op.f("ix_crawl_runs_definition_id"), table_name="crawl_runs")
    op.drop_column("crawl_runs", "allowed_ports")
    op.drop_column("crawl_runs", "allowed_content_types")
    op.drop_column("crawl_runs", "per_domain_concurrency")
    op.drop_column("crawl_runs", "global_concurrency")
    op.drop_column("crawl_runs", "max_duration_seconds")
    op.drop_column("crawl_runs", "generation")
    op.drop_column("crawl_runs", "definition_id")
    op.drop_index(op.f("ix_index_operations_status"), table_name="index_operations")
    op.drop_index("ix_index_operations_scheduler", table_name="index_operations")
    op.drop_index(op.f("ix_index_operations_run_id"), table_name="index_operations")
    op.drop_index(op.f("ix_index_operations_document_id"), table_name="index_operations")
    op.drop_index(op.f("ix_index_operations_available_at"), table_name="index_operations")
    op.drop_table("index_operations")
    op.drop_index(op.f("ix_extraction_attempts_run_id"), table_name="extraction_attempts")
    op.drop_index(op.f("ix_extraction_attempts_fetch_attempt_id"), table_name="extraction_attempts")
    op.drop_index(op.f("ix_extraction_attempts_document_id"), table_name="extraction_attempts")
    op.drop_table("extraction_attempts")
    op.drop_index("ix_observations_resource_observed", table_name="crawl_observations")
    op.drop_index(op.f("ix_crawl_observations_run_id"), table_name="crawl_observations")
    op.drop_index(op.f("ix_crawl_observations_resource_id"), table_name="crawl_observations")
    op.drop_index(op.f("ix_crawl_observations_outcome"), table_name="crawl_observations")
    op.drop_index(op.f("ix_crawl_observations_observed_at"), table_name="crawl_observations")
    op.drop_index(op.f("ix_crawl_observations_fetch_attempt_id"), table_name="crawl_observations")
    op.drop_index(op.f("ix_crawl_observations_document_id"), table_name="crawl_observations")
    op.drop_table("crawl_observations")
    op.drop_index(op.f("ix_worker_heartbeats_last_seen_at"), table_name="worker_heartbeats")
    op.drop_index(op.f("ix_worker_heartbeats_current_task_id"), table_name="worker_heartbeats")
    op.drop_table("worker_heartbeats")
    op.drop_index(op.f("ix_domain_leases_run_id"), table_name="domain_leases")
    op.drop_index("ix_domain_leases_host_expiry", table_name="domain_leases")
    op.drop_index(op.f("ix_domain_leases_host"), table_name="domain_leases")
    op.drop_index(op.f("ix_domain_leases_expires_at"), table_name="domain_leases")
    op.drop_table("domain_leases")
    op.drop_index(op.f("ix_pipeline_tasks_task_type"), table_name="pipeline_tasks")
    op.drop_index(op.f("ix_pipeline_tasks_status"), table_name="pipeline_tasks")
    op.drop_index("ix_pipeline_tasks_scheduler", table_name="pipeline_tasks")
    op.drop_index(op.f("ix_pipeline_tasks_run_id"), table_name="pipeline_tasks")
    op.drop_index(op.f("ix_pipeline_tasks_lease_token"), table_name="pipeline_tasks")
    op.drop_index(op.f("ix_pipeline_tasks_lease_expires_at"), table_name="pipeline_tasks")
    op.drop_index(op.f("ix_pipeline_tasks_frontier_entry_id"), table_name="pipeline_tasks")
    op.drop_index(op.f("ix_pipeline_tasks_available_at"), table_name="pipeline_tasks")
    op.drop_table("pipeline_tasks")
    op.drop_index(op.f("ix_operational_incidents_status"), table_name="operational_incidents")
    op.drop_index(op.f("ix_operational_incidents_severity"), table_name="operational_incidents")
    op.drop_index(op.f("ix_operational_incidents_run_id"), table_name="operational_incidents")
    op.drop_index(
        op.f("ix_operational_incidents_incident_type"), table_name="operational_incidents"
    )
    op.drop_table("operational_incidents")
    op.drop_index(op.f("ix_metric_samples_run_id"), table_name="metric_samples")
    op.drop_index(op.f("ix_metric_samples_observed_at"), table_name="metric_samples")
    op.drop_index("ix_metric_samples_name_time", table_name="metric_samples")
    op.drop_index(op.f("ix_metric_samples_metric_name"), table_name="metric_samples")
    op.drop_table("metric_samples")
    op.drop_index(op.f("ix_web_resources_next_recrawl_at"), table_name="web_resources")
    op.drop_index(op.f("ix_web_resources_last_checked_at"), table_name="web_resources")
    op.drop_index(op.f("ix_web_resources_last_changed_at"), table_name="web_resources")
    op.drop_index(op.f("ix_web_resources_host"), table_name="web_resources")
    op.drop_index(op.f("ix_web_resources_definition_id"), table_name="web_resources")
    op.drop_index(op.f("ix_web_resources_current_document_id"), table_name="web_resources")
    op.drop_table("web_resources")
    op.drop_index(op.f("ix_duplicate_clusters_definition_id"), table_name="duplicate_clusters")
    op.drop_table("duplicate_clusters")
    op.drop_index(op.f("ix_index_builds_status"), table_name="index_builds")
    op.drop_table("index_builds")
    op.drop_index(op.f("ix_crawl_definitions_next_run_at"), table_name="crawl_definitions")
    op.drop_index(op.f("ix_crawl_definitions_enabled"), table_name="crawl_definitions")
    op.drop_table("crawl_definitions")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    for enum_name in (
        "index_operation_status",
        "observation_outcome",
        "change_kind",
        "pipeline_task_status",
        "pipeline_task_type",
        "incident_status",
        "index_build_status",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
    # ### end Alembic commands ###
